version: '3.8'

services:
  app:
    container_name: nao
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app                      # Mount direktori aplikasi ke dalam container
      - ./sessions:/app/sessions    # Mount folder database ke dalam container (di luar container)
      - /app/node_modules           # Memastikan node_modules tidak ikut di-mount dari host
    environment:
      NODE_ENV: production
    command: "node index.js"
    restart: unless-stopped
